# Generated by Django 5.0.1 on 2024-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
